In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Import ML Libaries 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Import Dataset from sklearn 
from sklearn.datasets import load_iris
from sklearn import metrics

In [2]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
iris_df = pd.DataFrame(data= iris.data, columns= iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
target_df = pd.DataFrame(data= iris.target, columns= ['species'])
target_df

species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]

In [6]:
def converter(specie):
    if specie == 0:
        return 'setosa'
    elif specie == 1:
        return 'versicolor'
    else:
        return 'virginica'

In [7]:
target_df['species'] = target_df['species'].apply(converter)
target_df

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [8]:
iris_df = pd.concat([iris_df, target_df], axis= 1)


In [9]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [10]:
 
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [11]:
target_df = pd.DataFrame(columns= ['species'], data= iris.target)

In [12]:
target_df

species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]

In [13]:
iris_df.drop(columns="species",axis=1,inplace=True)

In [14]:
iris_df = pd.concat([iris_df, target_df], axis= 1)

In [15]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [16]:
X= iris_df.drop(labels= 'sepal length (cm)', axis= 1)
y= iris_df['sepal length (cm)']
print(X)
print(y)

     sepal width (cm)  petal length (cm)  petal width (cm)  species
0                 3.5                1.4               0.2        0
1                 3.0                1.4               0.2        0
2                 3.2                1.3               0.2        0
3                 3.1                1.5               0.2        0
4                 3.6                1.4               0.2        0
..                ...                ...               ...      ...
145               3.0                5.2               2.3        2
146               2.5                5.0               1.9        2
147               3.0                5.2               2.0        2
148               3.4                5.4               2.3        2
149               3.0                5.1               1.8        2

[150 rows x 4 columns]
0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, d

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size= 0.33, random_state= 102)

In [18]:
X_train

sepal width (cm)  petal length (cm)  petal width (cm)  species
122               2.8                6.7               2.0        2
50                3.2                4.7               1.4        1
116               3.0                5.5               1.8        2
136               3.4                5.6               2.4        2
133               2.8                5.1               1.5        2
..                ...                ...               ...      ...
66                3.0                4.5               1.5        1
111               2.7                5.3               1.9        2
114               2.8                5.1               2.4        2
78                2.9                4.5               1.5        1
0                 3.5                1.4               0.2        0

[100 rows x 4 columns]

In [19]:
y_train

122    7.7
50     7.0
116    6.5
136    6.3
133    6.3
      ... 
66     5.6
111    6.4
114    5.8
78     6.0
0      5.1
Name: sepal length (cm), Length: 100, dtype: float64

In [20]:
X_test

sepal width (cm)  petal length (cm)  petal width (cm)  species
8                 2.9                1.4               0.2        0
103               2.9                5.6               1.8        2
65                3.1                4.4               1.4        1
82                2.7                3.9               1.2        1
117               3.8                6.7               2.2        2
34                3.1                1.5               0.2        0
11                3.4                1.6               0.2        0
10                3.7                1.5               0.2        0
98                2.5                3.0               1.1        1
86                3.1                4.7               1.5        1
146               2.5                5.0               1.9        2
52                3.1                4.9               1.5        1
29                3.2                1.6               0.2        0
138               3.0                4.8               1.8        2
105               3.0                6.6               2.1        2
5                 3.9                1.7               0.4        0
2                 3.2                1.3               0.2        0
102               3.0                5.9               2.1        2
40                3.5                1.3               0.3        0
142               2.7                5.1               1.9        2
21                3.7                1.5               0.4        0
147               3.0                5.2               2.0        2
57                2.4                3.3               1.0        1
70                3.2                4.8               1.8        1
48                3.7                1.5               0.2        0
87                2.3                4.4               1.3        1
130               2.8                6.1               1.9        2
101               2.7                5.1               1.9        2
137               3.1                5.5               1.8        2
16                3.9                1.3               0.4        0
32                4.1                1.5               0.1        0
97                2.9                4.3               1.3        1
33                4.2                1.4               0.2        0
106               2.5                4.5               1.7        2
62                2.2                4.0               1.0        1
17                3.5                1.4               0.3        0
119               2.2                5.0               1.5        2
109               3.6                6.1               2.5        2
30                3.1                1.6               0.2        0
47                3.2                1.4               0.2        0
132               2.8                5.6               2.2        2
63                2.9                4.7               1.4        1
46                3.8                1.6               0.2        0
99                2.8                4.1               1.3        1
100               3.3                6.0               2.5        2
36                3.5                1.3               0.2        0
61                3.0                4.2               1.5        1
59                2.7                3.9               1.4        1
9                 3.1                1.5               0.1        0
55                2.8                4.5               1.3        1

In [21]:
y_test

8      4.4
103    6.3
65     6.7
82     5.8
117    7.7
34     4.9
11     4.8
10     5.4
98     5.1
86     6.7
146    6.3
52     6.9
29     4.7
138    6.0
105    7.6
5      5.4
2      4.7
102    7.1
40     5.0
142    5.8
21     5.1
147    6.5
57     4.9
70     5.9
48     5.3
87     6.3
130    7.4
101    5.8
137    6.4
16     5.4
32     5.2
97     6.2
33     5.5
106    4.9
62     6.0
17     5.1
119    6.0
109    7.2
30     4.8
47     4.6
132    6.4
63     6.1
46     5.1
99     5.7
100    6.3
36     5.5
61     5.9
59     5.2
9      4.9
55     5.7
Name: sepal length (cm), dtype: float64

In [22]:
X_train.shape

(100, 4)

In [23]:
X_test.shape

(50, 4)

In [24]:
lr = LinearRegression()

In [25]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [26]:

LNR2= lr.score(X_test,y_test)
LNR2

0.8578185306227293

In [27]:
lr.predict(X_test)

array([4.62552317, 6.65940325, 6.26263465, 5.7284934 , 7.86015755,
       4.82112282, 5.07985033, 5.19988992, 5.01068709, 6.43812155,
       5.95828318, 6.57680945, 4.95359463, 6.16777948, 7.31833575,
       5.39974361, 4.74556277, 6.83292808, 4.90240136, 6.15388283,
       5.13480001, 6.38006537, 5.18813605, 6.47295848, 5.19988992,
       5.79015681, 6.9104502 , 6.15388283, 6.716315  , 5.1223678 ,
       5.48494628, 6.09957996, 5.44618522, 5.67665333, 5.54728802,
       4.97174531, 5.89907946, 7.22020326, 4.89046678, 4.81490672,
       6.46609557, 6.34441081, 5.33236173, 5.8977642 , 6.96147575,
       4.93494632, 6.02827394, 5.66340349, 4.85366778, 6.17514001])

In [28]:
lr.predict(X_test)

array([4.62552317, 6.65940325, 6.26263465, 5.7284934 , 7.86015755,
       4.82112282, 5.07985033, 5.19988992, 5.01068709, 6.43812155,
       5.95828318, 6.57680945, 4.95359463, 6.16777948, 7.31833575,
       5.39974361, 4.74556277, 6.83292808, 4.90240136, 6.15388283,
       5.13480001, 6.38006537, 5.18813605, 6.47295848, 5.19988992,
       5.79015681, 6.9104502 , 6.15388283, 6.716315  , 5.1223678 ,
       5.48494628, 6.09957996, 5.44618522, 5.67665333, 5.54728802,
       4.97174531, 5.89907946, 7.22020326, 4.89046678, 4.81490672,
       6.46609557, 6.34441081, 5.33236173, 5.8977642 , 6.96147575,
       4.93494632, 6.02827394, 5.66340349, 4.85366778, 6.17514001])

In [29]:
y_pred_test = lr.predict(X_test)
y_pred_test

array([4.62552317, 6.65940325, 6.26263465, 5.7284934 , 7.86015755,
       4.82112282, 5.07985033, 5.19988992, 5.01068709, 6.43812155,
       5.95828318, 6.57680945, 4.95359463, 6.16777948, 7.31833575,
       5.39974361, 4.74556277, 6.83292808, 4.90240136, 6.15388283,
       5.13480001, 6.38006537, 5.18813605, 6.47295848, 5.19988992,
       5.79015681, 6.9104502 , 6.15388283, 6.716315  , 5.1223678 ,
       5.48494628, 6.09957996, 5.44618522, 5.67665333, 5.54728802,
       4.97174531, 5.89907946, 7.22020326, 4.89046678, 4.81490672,
       6.46609557, 6.34441081, 5.33236173, 5.8977642 , 6.96147575,
       4.93494632, 6.02827394, 5.66340349, 4.85366778, 6.17514001])

In [30]:
y_pred_train = lr.predict(X_train)
y_pred_train

array([7.29396896, 6.53379436, 6.65318715, 6.77977275, 6.34719051,
       5.57669496, 6.7534439 , 5.23047282, 5.47530367, 7.20876629,
       6.60019953, 5.01476041, 5.28788218, 6.37581134, 6.30761181,
       6.88362373, 5.07431256, 4.14486716, 6.04577782, 4.82112282,
       6.2762144 , 6.23630579, 4.68865102, 4.87803457, 6.53183229,
       5.09996308, 6.01208532, 6.89409387, 6.430441  , 4.98843155,
       5.1250082 , 6.45627224, 5.73470951, 6.09957996, 5.50231086,
       5.73128299, 4.67621882, 5.14919428, 6.51793564, 7.14481092,
       5.61417229, 6.17939405, 6.36256149, 6.2824305 , 6.75540596,
       6.3381947 , 5.93227122, 4.90861746, 6.0240199 , 6.35062691,
       6.67362981, 5.36916072, 4.94541646, 5.9039803 , 5.07363422,
       5.92573822, 4.79004231, 4.51316412, 6.12590881, 4.82733892,
       5.46551186, 5.18124162, 6.92630892, 6.030236  , 5.6390367 ,
       6.54557975, 7.12616261, 6.04773988, 5.512781  , 6.47803015,
       4.74556277, 4.72119598, 5.01050637, 5.01050637, 6.73103

In [31]:
print('Predicted Sepal lenght (cm):', y_pred_test)
print('Actual Sepal width Length (cm):',y_test)

Predicted Sepal lenght (cm): [4.62552317 6.65940325 6.26263465 5.7284934  7.86015755 4.82112282
 5.07985033 5.19988992 5.01068709 6.43812155 5.95828318 6.57680945
 4.95359463 6.16777948 7.31833575 5.39974361 4.74556277 6.83292808
 4.90240136 6.15388283 5.13480001 6.38006537 5.18813605 6.47295848
 5.19988992 5.79015681 6.9104502  6.15388283 6.716315   5.1223678
 5.48494628 6.09957996 5.44618522 5.67665333 5.54728802 4.97174531
 5.89907946 7.22020326 4.89046678 4.81490672 6.46609557 6.34441081
 5.33236173 5.8977642  6.96147575 4.93494632 6.02827394 5.66340349
 4.85366778 6.17514001]
Actual Sepal width Length (cm): 8      4.4
103    6.3
65     6.7
82     5.8
117    7.7
34     4.9
11     4.8
10     5.4
98     5.1
86     6.7
146    6.3
52     6.9
29     4.7
138    6.0
105    7.6
5      5.4
2      4.7
102    7.1
40     5.0
142    5.8
21     5.1
147    6.5
57     4.9
70     5.9
48     5.3
87     6.3
130    7.4
101    5.8
137    6.4
16     5.4
32     5.2
97     6.2
33     5.5
106    4.9
62    

In [32]:
MAE_train = metrics.mean_absolute_error(y_train,y_pred_train)
MAE_test = metrics.mean_absolute_error(y_test ,y_pred_test)


print('MAE_train for the training dataset:',MAE_train)         
print('MAE_test for the test dataset:',MAE_test)      

MAE_train for the training dataset: 0.25016635588841823
MAE_test for the test dataset: 0.2532615031683697


In [33]:
RMSE_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred_train))
RMSE_test = np.sqrt(metrics.mean_squared_error(y_test, y_pred_test))

In [34]:
print('RMSE for training set is {}'.format(RMSE_train))
print('RMSE for test set is {}'.format(RMSE_test))

RMSE for training set is 0.3066400791175233
RMSE for test set is 0.30984383651614433


In [35]:
LNR=lr.score(X_test,y_pred_test)
LNR

1.0

# testing

In [36]:
iris_df.loc[28]

sepal length (cm)    5.2
sepal width (cm)     3.4
petal length (cm)    1.4
petal width (cm)     0.2
species              0.0
Name: 28, dtype: float64

In [37]:
d = {'sepal length' : [5.2],
    'sepal width' : [3.4],
    'petal length' : [1.4],
    'petal width' : [0.2],
    'species' : 0}

In [38]:
test_df=pd.DataFrame(data=d)
test_df

sepal length  sepal width  petal length  petal width  species
0           5.2          3.4           1.4          0.2        0

In [39]:
X_test=test_df.drop('sepal length',axis=1)
y_test=test_df['sepal length']

In [40]:
LNR3= lr.score(X_test,y_test)
LNR3

C:\softwares\anaconda\lib\site-packages\sklearn\metrics\_regression.py:582: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


nan

In [41]:
y_pred_test=lr.predict(X_test)
y_pred_test

array([4.94116242])

In [42]:
print('Predicted Sepal Length (cm):', y_pred_test[0])
print('Actual Sepal Length (cm):', 5.2)

Predicted Sepal Length (cm): 4.941162421157266
Actual Sepal Length (cm): 5.2


In [43]:
MAE_test = metrics.mean_absolute_error(y_test ,y_pred_test)
print('MAE_test for the test dataset:',MAE_test) 


MAE_test for the test dataset: 0.2588375788427344


In [44]:
RMSE_test = np.sqrt(metrics.mean_squared_error(y_test, y_pred_test))
print('RMSE for test set is {}'.format(RMSE_test))

RMSE for test set is 0.2588375788427344


In [45]:
print('Mean Absolute Error for test data::', mean_absolute_error(y_test, y_pred_test))
print('Mean Squared Error for test data::', mean_squared_error(y_test, y_pred_test))
print('Mean Root Squared Error for test data:', np.sqrt(mean_squared_error(y_test, y_pred_test)))

Mean Absolute Error for test data:: 0.2588375788427344
Mean Squared Error for test data:: 0.06699689222116874
Mean Root Squared Error for test data: 0.2588375788427344
