In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
%matplotlib inline
    from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import warnings


In [2]:
df=pd.read_csv('iris.csv')

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
def converter(a):
   if a=='setosa':
        return "0"
   elif a=='versicolor':
        return "1"
   elif a=='virginica':
        return "2"

In [6]:
df['species_converted']=df['species'].apply(converter)

In [7]:
df

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

    species_converted  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  
..                ...  
145                 2  
146                 2  
147                 2  
148                 2  
149                 2  

[150 rows x 6 columns]

In [8]:
df.loc[72:100]

sepal_length  sepal_width  petal_length  petal_width     species  \
72            6.3          2.5           4.9          1.5  versicolor   
73            6.1          2.8           4.7          1.2  versicolor   
74            6.4          2.9           4.3          1.3  versicolor   
75            6.6          3.0           4.4          1.4  versicolor   
76            6.8          2.8           4.8          1.4  versicolor   
77            6.7          3.0           5.0          1.7  versicolor   
78            6.0          2.9           4.5          1.5  versicolor   
79            5.7          2.6           3.5          1.0  versicolor   
80            5.5          2.4           3.8          1.1  versicolor   
81            5.5          2.4           3.7          1.0  versicolor   
82            5.8          2.7           3.9          1.2  versicolor   
83            6.0          2.7           5.1          1.6  versicolor   
84            5.4          3.0           4.5          1.5  versicolor   
85            6.0          3.4           4.5          1.6  versicolor   
86            6.7          3.1           4.7          1.5  versicolor   
87            6.3          2.3           4.4          1.3  versicolor   
88            5.6          3.0           4.1          1.3  versicolor   
89            5.5          2.5           4.0          1.3  versicolor   
90            5.5          2.6           4.4          1.2  versicolor   
91            6.1          3.0           4.6          1.4  versicolor   
92            5.8          2.6           4.0          1.2  versicolor   
93            5.0          2.3           3.3          1.0  versicolor   
94            5.6          2.7           4.2          1.3  versicolor   
95            5.7          3.0           4.2          1.2  versicolor   
96            5.7          2.9           4.2          1.3  versicolor   
97            6.2          2.9           4.3          1.3  versicolor   
98            5.1          2.5           3.0          1.1  versicolor   
99            5.7          2.8           4.1          1.3  versicolor   
100           6.3          3.3           6.0          2.5   virginica   

    species_converted  
72                  1  
73                  1  
74                  1  
75                  1  
76                  1  
77                  1  
78                  1  
79                  1  
80                  1  
81                  1  
82                  1  
83                  1  
84                  1  
85                  1  
86                  1  
87                  1  
88                  1  
89                  1  
90                  1  
91                  1  
92                  1  
93                  1  
94                  1  
95                  1  
96                  1  
97                  1  
98                  1  
99                  1  
100                 2

In [9]:
df.drop(columns='species',axis=1,inplace=True)

In [10]:
df

sepal_length  sepal_width  petal_length  petal_width species_converted
0             5.1          3.5           1.4          0.2                 0
1             4.9          3.0           1.4          0.2                 0
2             4.7          3.2           1.3          0.2                 0
3             4.6          3.1           1.5          0.2                 0
4             5.0          3.6           1.4          0.2                 0
..            ...          ...           ...          ...               ...
145           6.7          3.0           5.2          2.3                 2
146           6.3          2.5           5.0          1.9                 2
147           6.5          3.0           5.2          2.0                 2
148           6.2          3.4           5.4          2.3                 2
149           5.9          3.0           5.1          1.8                 2

[150 rows x 5 columns]

In [11]:
X=df.drop(labels='petal_width',axis=1)
y=df['petal_width']

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=12)

In [13]:
X_train.shape

(100, 4)

In [14]:
X_test.shape

(50, 4)

In [15]:
y_train.shape

(100,)

In [16]:
y_test.shape

(50,)

In [17]:
lr=LinearRegression()

In [18]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
lr.predict(X_test)

array([0.19838706, 1.77810515, 0.18860729, 1.2804848 , 2.17937819,
       2.03995958, 2.14708321, 0.23110794, 2.04998317, 0.28123752,
       1.48953817, 0.22013782, 0.17888187, 0.29964709, 1.36448523,
       2.14623141, 2.00037422, 1.32784816, 0.28166342, 1.39939734,
       0.13805181, 1.17436205, 1.79107703, 1.39705703, 0.42928593,
       1.89567826, 1.48048247, 1.37907335, 0.31982199, 0.01127391,
       0.21746634, 1.07796473, 2.08841856, 0.30775626, 1.94732935,
       0.35511962, 1.13829997, 1.11445271, 0.13686146, 1.05469245,
       0.91503002, 0.28500461, 0.20224888, 0.32249347, 0.1554605 ,
       0.24742102, 0.35898145, 0.1113436 , 2.14665731, 0.24851663])

In [21]:
lr.predict(X_test)

array([0.19838706, 1.77810515, 0.18860729, 1.2804848 , 2.17937819,
       2.03995958, 2.14708321, 0.23110794, 2.04998317, 0.28123752,
       1.48953817, 0.22013782, 0.17888187, 0.29964709, 1.36448523,
       2.14623141, 2.00037422, 1.32784816, 0.28166342, 1.39939734,
       0.13805181, 1.17436205, 1.79107703, 1.39705703, 0.42928593,
       1.89567826, 1.48048247, 1.37907335, 0.31982199, 0.01127391,
       0.21746634, 1.07796473, 2.08841856, 0.30775626, 1.94732935,
       0.35511962, 1.13829997, 1.11445271, 0.13686146, 1.05469245,
       0.91503002, 0.28500461, 0.20224888, 0.32249347, 0.1554605 ,
       0.24742102, 0.35898145, 0.1113436 , 2.14665731, 0.24851663])

In [23]:
y_pred_test = lr.predict(X_test)
y_pred_test

array([0.19838706, 1.77810515, 0.18860729, 1.2804848 , 2.17937819,
       2.03995958, 2.14708321, 0.23110794, 2.04998317, 0.28123752,
       1.48953817, 0.22013782, 0.17888187, 0.29964709, 1.36448523,
       2.14623141, 2.00037422, 1.32784816, 0.28166342, 1.39939734,
       0.13805181, 1.17436205, 1.79107703, 1.39705703, 0.42928593,
       1.89567826, 1.48048247, 1.37907335, 0.31982199, 0.01127391,
       0.21746634, 1.07796473, 2.08841856, 0.30775626, 1.94732935,
       0.35511962, 1.13829997, 1.11445271, 0.13686146, 1.05469245,
       0.91503002, 0.28500461, 0.20224888, 0.32249347, 0.1554605 ,
       0.24742102, 0.35898145, 0.1113436 , 2.14665731, 0.24851663])

In [24]:
y_pred_train = lr.predict(X_train)  
y_pred_train

array([2.04816349, 1.51128894, 1.43202349, 1.4526243 , 0.26482971,
       1.91585316, 1.18089536, 1.4389827 , 2.08899354, 0.19738617,
       1.8825573 , 0.36608974, 2.14665731, 1.83938693, 1.97017573,
       1.87158718, 1.39386492, 1.03646496, 0.99620988, 1.57029214,
       2.24983176, 0.21746634, 2.06447656, 2.30740079, 0.19738617,
       1.31153509, 0.29101729, 2.03008508, 2.22321828, 0.30785099,
       1.39596141, 1.15637838, 0.29153792, 0.25185783, 1.17126468,
       1.42643672, 1.32365517, 1.52435556, 2.08021466, 1.32909286,
       1.95668322, 0.17721127, 0.18207398, 1.24022972, 1.36266554,
       1.59246881, 0.23430005, 1.93201716, 1.00064669, 0.23597065,
       2.08145935, 2.20265048, 1.16458229, 1.89066647, 1.99845981,
       0.27513011, 0.46844539, 2.16974751, 1.28440098, 1.20231496,
       2.02756268, 0.25772142, 1.50919245, 1.28926369, 0.19361908,
       1.01586415, 1.34358625, 1.93049564, 1.94732935, 1.27170591,
       0.23654563, 1.93970043, 0.37362393, 1.98773351, 0.25128

In [30]:
print('Predicted Petal width (cm):', y_pred_test)
print('Actual Petal width Length (cm):', y_test)

Predicted Petal width (cm): [0.19838706 1.77810515 0.18860729 1.2804848  2.17937819 2.03995958
 2.14708321 0.23110794 2.04998317 0.28123752 1.48953817 0.22013782
 0.17888187 0.29964709 1.36448523 2.14623141 2.00037422 1.32784816
 0.28166342 1.39939734 0.13805181 1.17436205 1.79107703 1.39705703
 0.42928593 1.89567826 1.48048247 1.37907335 0.31982199 0.01127391
 0.21746634 1.07796473 2.08841856 0.30775626 1.94732935 0.35511962
 1.13829997 1.11445271 0.13686146 1.05469245 0.91503002 0.28500461
 0.20224888 0.32249347 0.1554605  0.24742102 0.35898145 0.1113436
 2.14665731 0.24851663]
Actual Petal width Length (cm): 40     0.3
146    1.9
38     0.2
99     1.3
143    2.3
116    1.8
148    2.3
39     0.2
135    2.3
23     0.5
66     1.5
16     0.4
31     0.4
21     0.4
50     1.4
125    1.8
108    1.8
61     1.5
6      0.3
72     1.5
1      0.2
71     1.3
126    1.8
78     1.5
24     0.2
145    2.3
77     1.7
90     1.2
11     0.2
41     0.3
17     0.3
81     1.0
103    1.8
33     0.2
101    

In [26]:
print('Intercept:',lr.intercept_)          # print the intercept 
print('Coefficients:',lr.coef_)  

Intercept: -0.20514553630413257
Coefficients: [-0.17408691  0.22846383  0.3648798   0.34221983]


In [27]:
MAE_train = metrics.mean_absolute_error(y_train,y_pred_train)
MAE_test = metrics.mean_absolute_error(y_test , y_pred_test)


print('MAE_train for the training dataset:',MAE_train)         
print('MAE_test for the test dataset:',MAE_test)         

MAE_train for the training dataset: 0.1255257711890862
MAE_test for the test dataset: 0.12212548158578128


In [28]:
RMSE_train = np.sqrt(metrics.mean_squared_error(y_train, y_pred_train))
RMSE_test = np.sqrt(metrics.mean_squared_error(y_test, y_pred_test))

In [29]:
print('RMSE for training set is {}'.format(RMSE_train))
print('RMSE for test set is {}'.format(RMSE_test))

RMSE for training set is 0.1750417752244237
RMSE for test set is 0.1540053515582444


# testing

In [105]:
df.loc[28]

sepal_length         5.2
sepal_width          3.4
petal_length         1.4
petal_width          0.2
species_converted      0
Name: 28, dtype: object

In [106]:
d = {'sepal length' : [5.2],
    'sepal width' : [3.4],
    'petal length' : [1.4],
    'petal width' : [0.2],
    'species' : 0}

In [107]:
test_df=pd.DataFrame(data=d)
test_df

sepal length  sepal width  petal length  petal width  species
0           5.2          3.4           1.4          0.2        0

In [108]:
X_test=test_df.drop('petal width',axis=1)
y_test=test_df['petal width']

In [109]:
y_pred_test=lr.predict(X_test)
y_pred_test

array([0.17721127])

In [110]:
print('Predicted petal width (cm):', y_pred_test[0])
print('Actual petal width (cm):', 0.2)

Predicted petal width (cm): 0.1772112698694175
Actual petal width (cm): 0.2


In [116]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred_test))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred_test))
print('Mean Root Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test)))

Mean Absolute Error: 0.022788730130582524
Mean Squared Error: 0.0005193262209645198
Mean Root Squared Error: 0.022788730130582524


In [4]:
print('HI')

HI


In [150]:
nums=[1,2,4,5]
target=6
def two_sum(nums,target):
    if len(nums)<=1:
        return False
    dixt={}
    for i in range(len(nums)):
        print('i m the value of i',i)
        print('i m the Nums[i]',nums[i])
        if nums[i] in dixt:
            print('i m the dictornary',dixt)
            return [dixt[nums[i]],i]
        else:
            dixt[target-nums[i]]=i
print(two_sum(nums,target))


     

i m the value of i 0
i m the Nums[i] 1
i m the value of i 1
i m the Nums[i] 2
i m the value of i 2
i m the Nums[i] 4
i m the dictornary {5: 0, 4: 1}
[1, 2]
